/**
 * Slate — master color definitions.
 *
 * The "master deck" is the small set of high-level color controls (~23) that
 * drive the entire theme through the derivation engine in `semantic.ts`.
 */

import type { Masters } from './types';

export interface MasterGroup {
  id: string;
  label: string;
}

export interface MasterDef {
  key: keyof Masters;
  label: string;
  group: string;
}

export const MASTER_GROUPS: MasterGroup[] = [
  { id: 'core', label: 'Surfaces' },
  { id: 'text', label: 'Text' },
  { id: 'accent', label: 'Accent' },
  { id: 'bubbles', label: 'Bubbles' },
  { id: 'status', label: 'Status' },
  { id: 'peers', label: 'Peer Colors' },
];

export const MASTER_DEFS: MasterDef[] = [
  { key: 'masterBg', label: 'Background', group: 'core' },
  { key: 'masterSurface', label: 'Surface', group: 'core' },
  { key: 'masterChatList', label: 'Chat List', group: 'core' },
  { key: 'masterHeader', label: 'Header', group: 'core' },
  { key: 'masterInput', label: 'Compose Bar', group: 'core' },
  { key: 'masterDivider', label: 'Divider', group: 'core' },
  { key: 'masterText', label: 'Primary Text', group: 'text' },
  { key: 'masterTextMuted', label: 'Muted Text', group: 'text' },
  { key: 'masterAccent', label: 'Accent', group: 'accent' },
  { key: 'masterBubbleIn', label: 'Bubble In', group: 'bubbles' },
  { key: 'masterBubbleOut', label: 'Bubble Out', group: 'bubbles' },
  { key: 'masterOnline', label: 'Online', group: 'status' },
  { key: 'masterDestructive', label: 'Destructive', group: 'status' },
  { key: 'masterPositive', label: 'Positive', group: 'status' },
  { key: 'masterServiceBg', label: 'Service Pill', group: 'status' },
  { key: 'masterPeer1', label: 'Peer 1', group: 'peers' },
  { key: 'masterPeer2', label: 'Peer 2', group: 'peers' },
  { key: 'masterPeer3', label: 'Peer 3', group: 'peers' },
  { key: 'masterPeer4', label: 'Peer 4', group: 'peers' },
  { key: 'masterPeer5', label: 'Peer 5', group: 'peers' },
  { key: 'masterPeer6', label: 'Peer 6', group: 'peers' },
  { key: 'masterPeer7', label: 'Peer 7', group: 'peers' },
  { key: 'masterPeer8', label: 'Peer 8 · Saved', group: 'peers' },
];

export interface Preset {
  label: string;
  masters: Masters;
}

export const PRESETS: Record<string, Preset> = {
  midnight: {
    label: 'Midnight',
    masters: {
      masterBg: '#0E1621',
      masterSurface: '#17212B',
      masterChatList: '#17212B',
      masterHeader: '#17212B',
      masterInput: '#17212B',
      masterDivider: '#0B141C',
      masterText: '#E9EEF2',
      masterTextMuted: '#8A99A5',
      masterAccent: '#3390EC',
      masterBubbleIn: '#182533',
      masterBubbleOut: '#2B5278',
      masterOnline: '#4FD164',
      masterDestructive: '#EF5350',
      masterPositive: '#4FD164',
      masterServiceBg: '#101B26',
      masterPeer1: '#E17076',
      masterPeer2: '#7BC862',
      masterPeer3: '#E5CA77',
      masterPeer4: '#65AADD',
      masterPeer5: '#A695E7',
      masterPeer6: '#EE7AAE',
      masterPeer7: '#6EC9CB',
      masterPeer8: '#FAA774',
    },
  },
  daylight: {
    label: 'Daylight',
    masters: {
      masterBg: '#FFFFFF',
      masterSurface: '#F4F4F5',
      masterChatList: '#FFFFFF',
      masterHeader: '#FFFFFF',
      masterInput: '#FFFFFF',
      masterDivider: '#E4E7EB',
      masterText: '#1B1F23',
      masterTextMuted: '#707A85',
      masterAccent: '#3390EC',
      masterBubbleIn: '#F1F3F5',
      masterBubbleOut: '#E4F3D7',
      masterOnline: '#4DC85A',
      masterDestructive: '#E33D3D',
      masterPositive: '#4DC85A',
      masterServiceBg: '#B9D6F2',
      masterPeer1: '#D2564A',
      masterPeer2: '#4FA85B',
      masterPeer3: '#C99A29',
      masterPeer4: '#3E8CD1',
      masterPeer5: '#8368C7',
      masterPeer6: '#CB5C93',
      masterPeer7: '#2F9E9E',
      masterPeer8: '#DB7F3E',
    },
  },
  nocturne: {
    label: 'Nocturne',
    masters: {
      masterBg: '#0B0C10',
      masterSurface: '#15171D',
      masterChatList: '#111318',
      masterHeader: '#15171D',
      masterInput: '#15171D',
      masterDivider: '#000000',
      masterText: '#EDEDF2',
      masterTextMuted: '#83849A',
      masterAccent: '#8C6CF0',
      masterBubbleIn: '#181A22',
      masterBubbleOut: '#3B2E6E',
      masterOnline: '#5FE3A6',
      masterDestructive: '#F0596B',
      masterPositive: '#5FE3A6',
      masterServiceBg: '#181A22',
      masterPeer1: '#F0596B',
      masterPeer2: '#5FE3A6',
      masterPeer3: '#F0C36C',
      masterPeer4: '#6CA8F0',
      masterPeer5: '#B88CF0',
      masterPeer6: '#F06CC6',
      masterPeer7: '#6CE3E0',
      masterPeer8: '#F0A16C',
    },
  },
  ember: {
    label: 'Ember',
    masters: {
      masterBg: '#161211',
      masterSurface: '#1F1917',
      masterChatList: '#1B1614',
      masterHeader: '#1F1917',
      masterInput: '#1F1917',
      masterDivider: '#0E0B0A',
      masterText: '#F3EAE3',
      masterTextMuted: '#A6958A',
      masterAccent: '#FF8A3D',
      masterBubbleIn: '#241C19',
      masterBubbleOut: '#5C3520',
      masterOnline: '#7FD858',
      masterDestructive: '#F0523F',
      masterPositive: '#7FD858',
      masterServiceBg: '#241C19',
      masterPeer1: '#E2604F',
      masterPeer2: '#7FBE55',
      masterPeer3: '#E0B04E',
      masterPeer4: '#4FA6D6',
      masterPeer5: '#B084D9',
      masterPeer6: '#DE6E9E',
      masterPeer7: '#4FBFB6',
      masterPeer8: '#FF8A3D',
    },
  },
  blossom: {
    label: 'Blossom',
    masters: {
      masterBg: '#FFF7F8',
      masterSurface: '#FDEEF0',
      masterChatList: '#FFF7F8',
      masterHeader: '#FFF7F8',
      masterInput: '#FFF7F8',
      masterDivider: '#F3DEE1',
      masterText: '#3A2429',
      masterTextMuted: '#8C6C72',
      masterAccent: '#E85D75',
      masterBubbleIn: '#FBE8EA',
      masterBubbleOut: '#F6C9D0',
      masterOnline: '#5FBE7A',
      masterDestructive: '#D64550',
      masterPositive: '#5FBE7A',
      masterServiceBg: '#F0B8C4',
      masterPeer1: '#D64550',
      masterPeer2: '#5FA65B',
      masterPeer3: '#C99A29',
      masterPeer4: '#4B8FC7',
      masterPeer5: '#9169C4',
      masterPeer6: '#C74E90',
      masterPeer7: '#3E9E97',
      masterPeer8: '#E0813E',
    },
  },
  forest: {
    label: 'Forest',
    masters: {
      masterBg: '#0F1712',
      masterSurface: '#182420',
      masterChatList: '#141E19',
      masterHeader: '#182420',
      masterInput: '#182420',
      masterDivider: '#0A100D',
      masterText: '#E8F0EA',
      masterTextMuted: '#8FA696',
      masterAccent: '#4FBF7F',
      masterBubbleIn: '#1C2A24',
      masterBubbleOut: '#2B4A3A',
      masterOnline: '#7FD858',
      masterDestructive: '#E0654F',
      masterPositive: '#7FD858',
      masterServiceBg: '#1C2A24',
      masterPeer1: '#E0654F',
      masterPeer2: '#7FD858',
      masterPeer3: '#D6BE5C',
      masterPeer4: '#5CA8D6',
      masterPeer5: '#9A8CE0',
      masterPeer6: '#D67FB0',
      masterPeer7: '#5CC9BE',
      masterPeer8: '#E0A15C',
    },
  },
  mono: {
    label: 'Mono',
    masters: {
      masterBg: '#151515',
      masterSurface: '#1E1E1E',
      masterChatList: '#1A1A1A',
      masterHeader: '#1E1E1E',
      masterInput: '#1E1E1E',
      masterDivider: '#0D0D0D',
      masterText: '#EDEDED',
      masterTextMuted: '#8A8A8A',
      masterAccent: '#5B9FED',
      masterBubbleIn: '#232323',
      masterBubbleOut: '#2A3A4A',
      masterOnline: '#6FCF7A',
      masterDestructive: '#E0574F',
      masterPositive: '#6FCF7A',
      masterServiceBg: '#232323',
      masterPeer1: '#C77C7C',
      masterPeer2: '#8FBE8F',
      masterPeer3: '#C7B77C',
      masterPeer4: '#7CA8C7',
      masterPeer5: '#A88FC7',
      masterPeer6: '#C77CAE',
      masterPeer7: '#7CC7BE',
      masterPeer8: '#C7997C',
    },
  },
};

export const DEFAULT_MASTERS: Masters = PRESETS.midnight.masters;
